### ISSUE TITLE
説明文とキャプチャ画像の乖離について

### ISSUE THREAD

**Issue by ts0818** [oracle-japan/paasdocs#75]
■ドキュメントについて（2020/10/04 11:20 時点）

「Oracle Functionsことはじめ」
https://oracle-japan.github.io/paasdocs/documents/faas/oraclefunctions/handson/getting-started/
を実施しようとしていますが、「1-1. VCN（ネットワーク）の作成」において、『"VPN接続およびインターネット接続性を持つVCN"を選択し、"ワークフローの起動"をクリックします。』と言う説明とキャプチャ画像が乖離しているように見えます。
どちらが正しいですか？（キャプチャ画像では「インターネット接続性を持つVCN」が赤枠で囲まれているため）

**Comment by tniita** [comment]
コメントありがとうございます。そして、対応が遅くなり申し訳ございません。
ご指摘の通り、説明文とキャプチャ画像に解離がありました。
ここでは、「インターネット接続性を持つVCN」が正しい手順になりますので、説明文を修正しました。
既にドキュメントに反映済みですので、お手数ですが、ご確認いただけますでしょうか。
問題なければ、その旨コメントいただけますと幸いでございます。

**Comment by ts0818** [comment]
ご対応ありがとうございます。
修正されてることが確認できました。
#75のissueをクローズさせていただきます。

**Comment by ts0818** [comment]
ご担当者様

ご連絡ありがとうございます。
上記について、修正が確認できましたので、
#75のissueをクローズさせていただきました。

ご対応ありがとうございました。
何卒よろしくお願いいたします。

2020年10月22日(木) 11:54 Takuya Niita <notifications@github.com>:

**Comment by tniita** [comment]
ご確認、そしてissueのクローズ対応ありがとうございます。
引き続き、よろしくお願いいたします。

**Comment by ts0818** [comment]
ご担当者

ご連絡ありがとうございます。
こちらこそ、お忙しいところ修正のご対応いただき
ありがとうございます。

何卒よろしくお願いいたします。

2020年10月22日(木) 21:16 Takuya Niita <notifications@github.com>:
